# Generated by Django 4.1.7 on 2023-04-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_buxoro'),
    ]

    operations = [
        migrations.AddField(
            model_name='namangan',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
